name: BattleRoyaleCore
version: '${project.version}'
main: net.mochidsuki.corsica.battleroyalecore.BattleRoyaleCore
api-version: 1.19
authors: [ Mochidsuki ]
description: Corsica's Battle Royale Core System

softdepend: [ PlaceholderAPI , ProtocolLib ]

commands:
  gameround:
    aliases: [gr]
    description: ゲームのラウンド進行状況
    permission: battleroyale2.command.gamelound
    permission-message: Permission denied
    usage: gr [int]
  brc:
    aliases: [battleroyalecore]
    description: BRC管理コマンド
    permission: battleroyale2.command.brg
    permission-message: Permission denied
    usage: gr reload
  debugerb:
    description: debug用
    permission: battleroyale2.command.debuger
    permission-message: Permission denied
    usage: Command usage
  mapgenerator:
    description: 全体マップ生成
    permission: battleroyale2.command.mapgenerator
    permission-message: Permission denied
    usage: Command usage